%w( merchant_manage_contract merchant_add_recurring_check merchant_add_recurring_credit_card merchant_manage_check_info merchant_manage_contract merchant_manage_credit_card_info merchant_manage_customer merchant_process_check_recurring_billing merchant_process_credit_card_recurring_billing process_credit_card report_get_card_trx report_get_card_trx_summary report_get_check_trx report_get_info report_get_open_batch_summary transact_process_check transact_process_credit_card transact_process_debit_card transact_process_ebt_card transact_process_gift_card transact_sample_token transact_valid_card transact_valid_card_length transact_valid_exp_date transact_valid_mod10
  ).each do |lib|
  require File.join(File.dirname(__FILE__), 'requests', lib)
end

module Payleap
  module Api
    include TransactValidMod10
  end
end
